# Generated by Django 2.0.2 on 2018-09-02 16:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Happiness', models.FloatField(default=0)),
                ('SalaryPerMonthEmpMix', models.FloatField(default=0)),
                ('FeeFree', models.FloatField(default=0)),
                ('SalaryPerHour', models.FloatField(default=0)),
                ('SalaryPerMonth', models.FloatField(default=0)),
                ('Suspiciousentry', models.CharField(blank=True, choices=[('Ok', 'Ok'), ('Weird', 'Weird')], default='Ok', max_length=20, null=True)),
                ('JobPosition', models.CharField(blank=True, default='None', max_length=200)),
                ('Experience', models.CharField(blank=True, choices=[('keineAngabe', 'keineAngabe'), ('1 Jahr', '1 Jahr'), ('3 Jahre', '3 Jahre'), (' 5 Jahre', ' 5 Jahre')], default='keineAngabe', max_length=20, null=True)),
                ('HoursPerWeekEmp', models.FloatField(default=0)),
                ('HoursSpentFree', models.FloatField(default=0)),
                ('HoursPerDayMix', models.FloatField(default=0)),
                ('DaysPerMonthMix', models.FloatField(default=0)),
                ('Genre', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('VideoAudioTextFree', models.CharField(blank=True, choices=[('keineAngabe', 'keineAngabe'), ('text', 'text'), ('audio', 'audio'), (' video', ' video')], default='keineAngabe', max_length=200, null=True)),
                ('AnalogDigitalFree', models.CharField(blank=True, choices=[('keineAngabe', 'keineAngabe'), ('Analog', 'Analog'), ('Digital', 'Digital'), ('Analog & Digital', 'Analog & Digital')], default='keineAngabe', max_length=200, null=True)),
                ('MinPerAudioFree', models.FloatField(default=0)),
                ('MinPerVideoFree', models.FloatField(default=0)),
                ('CharPerArticleFree', models.FloatField(default=0)),
                ('Comment', models.TextField(blank=True, default='Kein Kommentar', max_length=600, null=True)),
                ('Gegendarstellung', models.TextField(blank=True, default=None, max_length=600, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fairness', models.CharField(blank=True, choices=[('keineAngabe', 'keineAngabe'), ('Ja', 'Ja'), ('Hoelle', 'Hoelle'), ('Himmel', 'Himmel'), ('HoelleJa', 'HoelleJa'), ('HimmelJa', 'HimmelJa')], default='', max_length=20, null=True)),
                ('Suspiciousmedium', models.CharField(blank=True, choices=[('Ok', 'Ok'), ('Weird', 'Weird')], default='Ok', max_length=20, null=True)),
                ('mediumname', models.CharField(max_length=200)),
                ('freeoremployed', models.CharField(choices=[('fest', 'fest'), ('pauschal', 'pauschal'), ('frei', 'frei')], default='frei', max_length=10)),
                ('UpDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='datacollection',
            name='Medium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='honoradar.Medium'),
        ),
    ]
