# Generated by Django 2.0.2 on 2018-03-21 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DataCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Happiness', models.IntegerField(default=0)),
                ('SalaryPerMonthEmpMix', models.IntegerField(default=0)),
                ('FeeFree', models.IntegerField(default=0)),
                ('JobPosition', models.CharField(default='None', max_length=200)),
                ('Experience', models.CharField(choices=[('keineAngabe', 'keineAngabe'), ('1 Jahr', '1 Jahr'), ('3 Jahre', '3 Jahre'), (' 5 Jahre', ' 5 Jahre')], default='keineAngabe', max_length=10)),
                ('HoursPerWeekEmp', models.IntegerField(default=0)),
                ('HoursSpentFree', models.IntegerField(default=0)),
                ('HoursPerDayMix', models.IntegerField(default=0)),
                ('DaysPerMonthMix', models.IntegerField(default=0)),
                ('Genre', models.CharField(default='None', max_length=200)),
                ('MinPerAudioFree', models.IntegerField(default=0)),
                ('MinPerVideoFree', models.IntegerField(default=0)),
                ('CharPerArticleFree', models.IntegerField(default=0)),
                ('Comment', models.CharField(default='Kein Kommentar', max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediumname', models.CharField(max_length=200)),
                ('freeoremployed', models.CharField(choices=[('fest', 'fest'), ('pauschal', 'pauschal'), ('frei', 'frei')], default='frei', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='datacollection',
            name='Medium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='honoradar.Medium'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='honoradar.Question'),
        ),
    ]
