# Generated by Django 2.0.2 on 2018-04-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honoradar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacollection',
            name='AnalogDigitalFree',
            field=models.CharField(choices=[('keineAngabe', 'keineAngabe'), ('Analog', 'Analog'), ('Digital', 'Digital'), ('Analog & Digital', 'Analog & Digital')], default='keineAngabe', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='Comment',
            field=models.TextField(default='Kein Kommentar', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='VideoAudioTextFree',
            field=models.CharField(choices=[('keineAngabe', 'keineAngabe'), ('text', 'text'), ('audio', 'audio'), (' video', ' video')], default='keineAngabe', max_length=200, null=True),
        ),
    ]
