# Generated by Django 2.0.2 on 2018-05-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honoradar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacollection',
            name='Genre',
            field=models.CharField(blank=True, default='None', max_length=200),
        ),
    ]
