# Generated by Django 2.0.2 on 2018-03-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honoradar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacollection',
            name='SalaryPerHours',
            field=models.IntegerField(default=0),
        ),
    ]
