# Generated by Django 2.0.2 on 2018-03-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honoradar', '0002_datacollection_salaryperhours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datacollection',
            old_name='SalaryPerHours',
            new_name='SalaryPerHour',
        ),
        migrations.AddField(
            model_name='datacollection',
            name='SalaryPerMonth',
            field=models.IntegerField(default=0),
        ),
    ]
