# Generated by Django 2.0.2 on 2018-04-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honoradar', '0002_auto_20180413_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacollection',
            name='AnalogDigitalFree',
            field=models.CharField(choices=[('keineAngabe', 'keineAngabe'), ('Analog', 'Analog'), ('Digital', 'Digital'), ('Analog & Digital', 'Analog & Digital')], default='keineAngabe', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='Experience',
            field=models.CharField(choices=[('keineAngabe', 'keineAngabe'), ('1 Jahr', '1 Jahr'), ('3 Jahre', '3 Jahre'), (' 5 Jahre', ' 5 Jahre')], default='keineAngabe', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='JobPosition',
            field=models.TextField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='VideoAudioTextFree',
            field=models.CharField(choices=[('keineAngabe', 'keineAngabe'), ('text', 'text'), ('audio', 'audio'), (' video', ' video')], default='keineAngabe', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='medium',
            name='mediumname',
            field=models.TextField(max_length=200),
        ),
    ]
