# Generated by Django 2.0.2 on 2018-05-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honoradar', '0002_auto_20180510_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacollection',
            name='AnalogDigitalFree',
            field=models.CharField(choices=[('keineAngabe', 'keineAngabe'), ('Analog', 'Analog'), ('Digital', 'Digital'), ('Analog & Digital', 'Analog & Digital')], default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='Comment',
            field=models.TextField(default='', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='Experience',
            field=models.CharField(choices=[('keineAngabe', 'keineAngabe'), ('1 Jahr', '1 Jahr'), ('3 Jahre', '3 Jahre'), (' 5 Jahre', ' 5 Jahre')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='JobPosition',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='VideoAudioTextFree',
            field=models.CharField(choices=[('keineAngabe', 'keineAngabe'), ('text', 'text'), ('audio', 'audio'), (' video', ' video')], default='', max_length=200, null=True),
        ),
    ]
