# Generated by Django 2.0.2 on 2018-05-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honoradar', '0003_auto_20180510_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacollection',
            name='AnalogDigitalFree',
            field=models.CharField(blank=True, choices=[('keineAngabe', 'keineAngabe'), ('Analog', 'Analog'), ('Digital', 'Digital'), ('Analog & Digital', 'Analog & Digital')], default='keineAngabe', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='Comment',
            field=models.TextField(blank=True, default='Kein Kommentar', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='Experience',
            field=models.CharField(blank=True, choices=[('keineAngabe', 'keineAngabe'), ('1 Jahr', '1 Jahr'), ('3 Jahre', '3 Jahre'), (' 5 Jahre', ' 5 Jahre')], default='keineAngabe', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='JobPosition',
            field=models.CharField(blank=True, default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='VideoAudioTextFree',
            field=models.CharField(blank=True, choices=[('keineAngabe', 'keineAngabe'), ('text', 'text'), ('audio', 'audio'), (' video', ' video')], default='keineAngabe', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='fairness',
            field=models.CharField(blank=True, choices=[('keineAngabe', 'keineAngabe'), ('Ja', 'Ja')], default='', max_length=20, null=True),
        ),
    ]
