# Generated by Django 2.0.2 on 2018-03-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honoradar', '0004_auto_20180325_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacollection',
            name='VideoAudioTextFree',
            field=models.CharField(choices=[('keineAngabe', 'keineAngabe'), ('text', 'text'), ('audio', 'audio'), (' video', ' video')], default='keineAngabe', max_length=10, null=True),
        ),
    ]
