# Generated by Django 2.0.2 on 2018-05-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honoradar', '0004_auto_20180510_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacollection',
            name='Experience',
            field=models.CharField(blank=True, choices=[('keineAngabe', 'keineAngabe'), ('1 Jahr', '1 Jahr'), ('3 Jahre', '3 Jahre'), (' 5 Jahre', ' 5 Jahre')], default='keineAngabe', max_length=20, null=True),
        ),
    ]
