# Generated by Django 2.0.2 on 2018-03-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honoradar', '0005_datacollection_videoaudiotextfree'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacollection',
            name='AnalogDigitalFree',
            field=models.CharField(choices=[('keineAngabe', 'keineAngabe'), ('Analog', 'Analog'), ('Digital', 'Digital'), ('Analog & Digital', 'Analog & Digital')], default='keineAngabe', max_length=10, null=True),
        ),
    ]
