# Generated by Django 2.0.2 on 2018-05-26 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honoradar', '0005_auto_20180510_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacollection',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='Genre',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
    ]
