# Generated by Django 2.0.2 on 2018-05-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honoradar', '0006_auto_20180526_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacollection',
            name='CharPerArticleFree',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='DaysPerMonthMix',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='FeeFree',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='Happiness',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='HoursPerDayMix',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='HoursPerWeekEmp',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='HoursSpentFree',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='MinPerAudioFree',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='MinPerVideoFree',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='SalaryPerHour',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='SalaryPerMonth',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='SalaryPerMonthEmpMix',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
