# Generated by Django 2.0.2 on 2018-05-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honoradar', '0008_auto_20180526_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacollection',
            name='fairness',
        ),
        migrations.AddField(
            model_name='medium',
            name='fairness',
            field=models.CharField(blank=True, choices=[('keineAngabe', 'keineAngabe'), ('Ja', 'Ja'), ('Hoelle', 'Hoelle'), ('Himmel', 'Himmel')], default='', max_length=20, null=True),
        ),
    ]
