# Generated by Django 2.0.2 on 2018-03-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honoradar', '0015_auto_20180301_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacollection',
            name='Comment',
            field=models.CharField(default='Kein Kommentar', max_length=600),
        ),
    ]
