# Generated by Django 2.0.2 on 2018-03-02 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('honoradar', '0016_auto_20180301_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datacollection',
            old_name='ProductType',
            new_name='Genre',
        ),
    ]
