# Generated by Django 2.0 on 2018-04-09 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('honoradar', '0017_auto_20180302_0646'),
        ('honoradar', '0007_auto_20180325_2201'),
    ]

    operations = [
    ]
